name: m_posw_android
description: "App POS para Android con WebView e impresión Bluetooth"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  print_bluetooth_thermal: ^1.1.9
  esc_pos_utils_plus: ^2.0.4
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo_pos.png"
  adaptive_icon_foreground: "assets/logo_pos.png"
  adaptive_icon_background: "#0EA5E9"
  remove_alpha_ios: true
  keep_name: true