import 'package:flutter/material.dart';
import 'package:material_symbols_icons/symbols.dart';

const List<String> materialSymbolNames = [
  'account_balance',
  'account_balance_wallet',
  'account_box',
  'account_circle',
  'add',
  'add_circle',
  'add_circle_outline',
  'add_shopping_cart',
  'add_task',
  'admin_panel_settings',
  'alarm',
  'alarm_on',
  'album',
  'analytics',
  'android',
  'announcement',
  'api',
  'apps',
  'archive',
  'arrow_back',
  'arrow_circle_down',
  'arrow_circle_up',
  'arrow_forward',
  'article',
  'assessment',
  'attach_file',
  'attach_money',
  'attribution',
  'auto_awesome',
  'auto_fix_high',
  'autorenew',
  'backspace',
  'badge',
  'bakery_dining',
  'bar_chart',
  'battery_full',
  'beach_access',
  'bed',
  'bolt',
  'book',
  'bookmark',
  'bookmark_add',
  'border_color',
  'brush',
  'bug_report',
  'build',
  'business',
  'cake',
  'calculate',
  'calendar_month',
  'call',
  'camera_alt',
  'camping',
  'cancel',
  'cancel_presentation',
  'card_giftcard',
  'card_membership',
  'card_travel',
  'category',
  'change_circle',
  'check',
  'check_circle',
  'checkroom',
  'children',
  'chip',
  'church',
  'circle',
  'cleaning_services',
  'clear',
  'close',
  'cloud',
  'cloud_download',
  'cloud_upload',
  'coffee',
  'color_lens',
  'comment',
  'commute',
  'confirmation_number',
  'contact_mail',
  'contact_phone',
  'content_cut',
  'content_paste',
  'copy_all',
  'credit_card',
  'currency_exchange',
  'dashboard',
  'data_usage',
  'date_range',
  'delete',
  'delete_forever',
  'description',
  'desktop_windows',
  'device_hub',
  'devices',
  'dialpad',
  'directions',
  'directions_bike',
  'directions_bus',
  'directions_car',
  'directions_walk',
  'document_scanner',
  'done',
  'done_all',
  'download',
  'drafts',
  'drag_handle',
  'draw',
  'drive_file_move',
  'edit',
  'edit_note',
  'email',
  'emoji_events',
  'error',
  'event',
  'event_available',
  'event_busy',
  'expand_less',
  'expand_more',
  'explore',
  'extension',
  'face',
  'favorite',
  'favorite_border',
  'feed',
  'file_copy',
  'file_download',
  'file_present',
  'filter_alt',
  'fingerprint',
  'flag',
  'flight',
  'folder',
  'folder_open',
  'format_list_bulleted',
  'format_list_numbered',
  'forum',
  'grid_view',
  'group',
  'group_add',
  'handyman',
  'hardware',
  'headphones',
  'help',
  'help_outline',
  'history',
  'home',
  'home_filled',
  'home_work',
  'hourglass_empty',
  'image',
  'image_search',
  'inbox',
  'info',
  'inventory',
  'key',
  'keyboard',
  'language',
  'laptop',
  'launch',
  'layers',
  'lightbulb',
  'link',
  'list',
  'local_atm',
  'local_bar',
  'local_cafe',
  'local_dining',
  'local_grocery_store',
  'local_hospital',
  'local_offer',
  'local_shipping',
  'location_on',
  'lock',
  'lock_open',
  'login',
  'logout',
  'loyalty',
  'mail',
  'map',
  'mark_email_read',
  'mark_email_unread',
  'medication',
  'menu',
  'mic',
  'mic_off',
  'mode_edit',
  'monitor_heart',
  'mood',
  'more_horiz',
  'more_vert',
  'mouse',
  'move_to_inbox',
  'movie',
  'music_note',
  'my_location',
  'navigation',
  'near_me',
  'notifications',
  'notifications_active',
  'notifications_off',
  'palette',
  'pan_tool',
  'payment',
  'people',
  'percent',
  'person',
  'person_add',
  'person_pin',
  'pets',
  'phone',
  'photo_camera',
  'pie_chart',
  'place',
  'play_arrow',
  'playlist_add',
  'point_of_sale',
  'price_check',
  'print',
  'qr_code',
  'qr_code_scanner',
  'query_stats',
  'receipt',
  'recent_actors',
  'refresh',
  'remove',
  'remove_circle',
  'report',
  'restaurant',
  'rocket_launch',
  'router',
  'save',
  'schedule',
  'school',
  'search',
  'security',
  'sell',
  'send',
  'settings',
  'settings_suggest',
  'share',
  'shield',
  'shopping_bag',
  'shopping_cart',
  'shopping_cart_checkout',
  'smartphone',
  'sms',
  'sort',
  'spa',
  'speed',
  'star',
  'store',
  'storefront',
  'support_agent',
  'sync',
  'tag',
  'task_alt',
  'terminal',
  'thumb_down',
  'thumb_up',
  'timeline',
  'today',
  'toggle_off',
  'toggle_on',
  'touch_app',
  'train',
  'trending_up',
  'tune',
  'undo',
  'update',
  'upload',
  'verified',
  'visibility',
  'visibility_off',
  'wallet',
  'warning',
  'watch',
  'wifi',
  'work',
  'wrap_text',
  'zoom_in',
  'zoom_out',
];

final Map<String, IconData> materialSymbolIconMap = {
  'account_balance': Symbols.account_balance,
  'account_balance_wallet': Symbols.account_balance_wallet,
  'account_box': Symbols.account_box,
  'account_circle': Symbols.account_circle,
  'add': Symbols.add,
  'add_circle': Symbols.add_circle,
  'add_circle_outline': Symbols.add_circle_outline,
  'add_shopping_cart': Symbols.add_shopping_cart,
  'add_task': Symbols.add_task,
  'admin_panel_settings': Symbols.admin_panel_settings,
  'alarm': Symbols.alarm,
  'alarm_on': Symbols.alarm_on,
  'album': Symbols.album,
  'analytics': Symbols.analytics,
  'android': Symbols.android,
  'announcement': Symbols.announcement,
  'api': Symbols.api,
  'apps': Symbols.apps,
  'archive': Symbols.archive,
  'arrow_back': Symbols.arrow_back,
  'arrow_circle_down': Symbols.arrow_circle_down,
  'arrow_circle_up': Symbols.arrow_circle_up,
  'arrow_forward': Symbols.arrow_forward,
  'article': Symbols.article,
  'assessment': Symbols.assessment,
  'attach_file': Symbols.attach_file,
  'attach_money': Symbols.attach_money,
  'attribution': Symbols.attribution,
  'auto_awesome': Symbols.auto_awesome,
  'auto_fix_high': Symbols.auto_fix_high,
  'autorenew': Symbols.autorenew,
  'backspace': Symbols.backspace,
  'badge': Symbols.badge,
  'bakery_dining': Symbols.bakery_dining,
  'bar_chart': Symbols.bar_chart,
  'battery_full': Symbols.battery_full,
  'beach_access': Symbols.beach_access,
  'bed': Symbols.bed,
  'bolt': Symbols.bolt,
  'book': Symbols.book,
  'bookmark': Symbols.bookmark,
  'bookmark_add': Symbols.bookmark_add,
  'border_color': Symbols.border_color,
  'brush': Symbols.brush,
  'bug_report': Symbols.bug_report,
  'build': Symbols.build,
  'business': Symbols.business,
  'cake': Symbols.cake,
  'calculate': Symbols.calculate,
  'calendar_month': Symbols.calendar_month,
  'call': Symbols.call,
  'camera_alt': Symbols.camera_alt,
  'camping': Symbols.camping,
  'cancel': Symbols.cancel,
  'cancel_presentation': Symbols.cancel_presentation,
  'card_giftcard': Symbols.card_giftcard,
  'card_membership': Symbols.card_membership,
  'card_travel': Symbols.card_travel,
  'category': Symbols.category,
  'change_circle': Symbols.change_circle,
  'check': Symbols.check,
  'check_circle': Symbols.check_circle,
  'checkroom': Symbols.checkroom,
  'children': Symbols.children,
  'chip': Symbols.chip,
  'church': Symbols.church,
  'circle': Symbols.circle,
  'cleaning_services': Symbols.cleaning_services,
  'clear': Symbols.clear,
  'close': Symbols.close,
  'cloud': Symbols.cloud,
  'cloud_download': Symbols.cloud_download,
  'cloud_upload': Symbols.cloud_upload,
  'coffee': Symbols.coffee,
  'color_lens': Symbols.color_lens,
  'comment': Symbols.comment,
  'commute': Symbols.commute,
  'confirmation_number': Symbols.confirmation_number,
  'contact_mail': Symbols.contact_mail,
  'contact_phone': Symbols.contact_phone,
  'content_cut': Symbols.content_cut,
  'content_paste': Symbols.content_paste,
  'copy_all': Symbols.copy_all,
  'credit_card': Symbols.credit_card,
  'currency_exchange': Symbols.currency_exchange,
  'dashboard': Symbols.dashboard,
  'data_usage': Symbols.data_usage,
  'date_range': Symbols.date_range,
  'delete': Symbols.delete,
  'delete_forever': Symbols.delete_forever,
  'description': Symbols.description,
  'desktop_windows': Symbols.desktop_windows,
  'device_hub': Symbols.device_hub,
  'devices': Symbols.devices,
  'dialpad': Symbols.dialpad,
  'directions': Symbols.directions,
  'directions_bike': Symbols.directions_bike,
  'directions_bus': Symbols.directions_bus,
  'directions_car': Symbols.directions_car,
  'directions_walk': Symbols.directions_walk,
  'document_scanner': Symbols.document_scanner,
  'done': Symbols.done,
  'done_all': Symbols.done_all,
  'download': Symbols.download,
  'drafts': Symbols.drafts,
  'drag_handle': Symbols.drag_handle,
  'draw': Symbols.draw,
  'drive_file_move': Symbols.drive_file_move,
  'edit': Symbols.edit,
  'edit_note': Symbols.edit_note,
  'email': Symbols.email,
  'emoji_events': Symbols.emoji_events,
  'error': Symbols.error,
  'event': Symbols.event,
  'event_available': Symbols.event_available,
  'event_busy': Symbols.event_busy,
  'expand_less': Symbols.expand_less,
  'expand_more': Symbols.expand_more,
  'explore': Symbols.explore,
  'extension': Symbols.extension,
  'face': Symbols.face,
  'favorite': Symbols.favorite,
  'favorite_border': Symbols.favorite_border,
  'feed': Symbols.feed,
  'file_copy': Symbols.file_copy,
  'file_download': Symbols.file_download,
  'file_present': Symbols.file_present,
  'filter_alt': Symbols.filter_alt,
  'fingerprint': Symbols.fingerprint,
  'flag': Symbols.flag,
  'flight': Symbols.flight,
  'folder': Symbols.folder,
  'folder_open': Symbols.folder_open,
  'format_list_bulleted': Symbols.format_list_bulleted,
  'format_list_numbered': Symbols.format_list_numbered,
  'forum': Symbols.forum,
  'grid_view': Symbols.grid_view,
  'group': Symbols.group,
  'group_add': Symbols.group_add,
  'handyman': Symbols.handyman,
  'hardware': Symbols.hardware,
  'headphones': Symbols.headphones,
  'help': Symbols.help,
  'help_outline': Symbols.help_outline,
  'history': Symbols.history,
  'home': Symbols.home,
  'home_filled': Symbols.home_filled,
  'home_work': Symbols.home_work,
  'hourglass_empty': Symbols.hourglass_empty,
  'image': Symbols.image,
  'image_search': Symbols.image_search,
  'inbox': Symbols.inbox,
  'info': Symbols.info,
  'inventory': Symbols.inventory,
  'key': Symbols.key,
  'keyboard': Symbols.keyboard,
  'language': Symbols.language,
  'laptop': Symbols.laptop,
  'launch': Symbols.launch,
  'layers': Symbols.layers,
  'lightbulb': Symbols.lightbulb,
  'link': Symbols.link,
  'list': Symbols.list,
  'local_atm': Symbols.local_atm,
  'local_bar': Symbols.local_bar,
  'local_cafe': Symbols.local_cafe,
  'local_dining': Symbols.local_dining,
  'local_grocery_store': Symbols.local_grocery_store,
  'local_hospital': Symbols.local_hospital,
  'local_offer': Symbols.local_offer,
  'local_shipping': Symbols.local_shipping,
  'location_on': Symbols.location_on,
  'lock': Symbols.lock,
  'lock_open': Symbols.lock_open,
  'login': Symbols.login,
  'logout': Symbols.logout,
  'loyalty': Symbols.loyalty,
  'mail': Symbols.mail,
  'map': Symbols.map,
  'mark_email_read': Symbols.mark_email_read,
  'mark_email_unread': Symbols.mark_email_unread,
  'medication': Symbols.medication,
  'menu': Symbols.menu,
  'mic': Symbols.mic,
  'mic_off': Symbols.mic_off,
  'mode_edit': Symbols.mode_edit,
  'monitor_heart': Symbols.monitor_heart,
  'mood': Symbols.mood,
  'more_horiz': Symbols.more_horiz,
  'more_vert': Symbols.more_vert,
  'mouse': Symbols.mouse,
  'move_to_inbox': Symbols.move_to_inbox,
  'movie': Symbols.movie,
  'music_note': Symbols.music_note,
  'my_location': Symbols.my_location,
  'navigation': Symbols.navigation,
  'near_me': Symbols.near_me,
  'notifications': Symbols.notifications,
  'notifications_active': Symbols.notifications_active,
  'notifications_off': Symbols.notifications_off,
  'palette': Symbols.palette,
  'pan_tool': Symbols.pan_tool,
  'payment': Symbols.payment,
  'people': Symbols.people,
  'percent': Symbols.percent,
  'person': Symbols.person,
  'person_add': Symbols.person_add,
  'person_pin': Symbols.person_pin,
  'pets': Symbols.pets,
  'phone': Symbols.phone,
  'photo_camera': Symbols.photo_camera,
  'pie_chart': Symbols.pie_chart,
  'place': Symbols.place,
  'play_arrow': Symbols.play_arrow,
  'playlist_add': Symbols.playlist_add,
  'point_of_sale': Symbols.point_of_sale,
  'price_check': Symbols.price_check,
  'print': Symbols.print,
  'qr_code': Symbols.qr_code,
  'qr_code_scanner': Symbols.qr_code_scanner,
  'query_stats': Symbols.query_stats,
  'receipt': Symbols.receipt,
  'recent_actors': Symbols.recent_actors,
  'refresh': Symbols.refresh,
  'remove': Symbols.remove,
  'remove_circle': Symbols.remove_circle,
  'report': Symbols.report,
  'restaurant': Symbols.restaurant,
  'rocket_launch': Symbols.rocket_launch,
  'router': Symbols.router,
  'save': Symbols.save,
  'schedule': Symbols.schedule,
  'school': Symbols.school,
  'search': Symbols.search,
  'security': Symbols.security,
  'sell': Symbols.sell,
  'send': Symbols.send,
  'settings': Symbols.settings,
  'settings_suggest': Symbols.settings_suggest,
  'share': Symbols.share,
  'shield': Symbols.shield,
  'shopping_bag': Symbols.shopping_bag,
  'shopping_cart': Symbols.shopping_cart,
  'shopping_cart_checkout': Symbols.shopping_cart_checkout,
  'smartphone': Symbols.smartphone,
  'sms': Symbols.sms,
  'sort': Symbols.sort,
  'spa': Symbols.spa,
  'speed': Symbols.speed,
  'star': Symbols.star,
  'store': Symbols.store,
  'storefront': Symbols.storefront,
  'support_agent': Symbols.support_agent,
  'sync': Symbols.sync,
  'tag': Symbols.tag,
  'task_alt': Symbols.task_alt,
  'terminal': Symbols.terminal,
  'thumb_down': Symbols.thumb_down,
  'thumb_up': Symbols.thumb_up,
  'timeline': Symbols.timeline,
  'today': Symbols.today,
  'toggle_off': Symbols.toggle_off,
  'toggle_on': Symbols.toggle_on,
  'touch_app': Symbols.touch_app,
  'train': Symbols.train,
  'trending_up': Symbols.trending_up,
  'tune': Symbols.tune,
  'undo': Symbols.undo,
  'update': Symbols.update,
  'upload': Symbols.upload,
  'verified': Symbols.verified,
  'visibility': Symbols.visibility,
  'visibility_off': Symbols.visibility_off,
  'wallet': Symbols.wallet,
  'warning': Symbols.warning,
  'watch': Symbols.watch,
  'wifi': Symbols.wifi,
  'work': Symbols.work,
  'wrap_text': Symbols.wrap_text,
  'zoom_in': Symbols.zoom_in,
  'zoom_out': Symbols.zoom_out,
};

IconData symbolFromName(String? name) {
  if (name == null) {
    return Symbols.category;
  }
  return materialSymbolIconMap[name] ?? Symbols.category;
}
